### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by sgarcia-dev** [antelle/kdbxweb#1]
Seeing this is v0.1.0 according to npmjs, I wasn't really sure if this was working but from https://antelle.github.io/keeweb/ , I figured it had to. However, I haven't been able to succesfully get this to even load. 

Loading kdbxweb/dist/kdbxweb.js on chrome returns an error:
Uncaught SyntaxError: Invalid regular expression: /[\-\.0-9A-Z_a-z\xC0-\xD6\xD8-\xF6\u00F8-\u02FF\u0370-\u037D\u037F-\u1FFF\u200C-\u200D\u2070-\u218F\u2C00-\u2FEF\u3001-\uD7FF\uF900-\uFDCF\uFDF0-\uFFFDÂ·Ì€-Í¯\ux203F-â€]/: Range out of order in character class

and trying to use "require(kdbxweb)" also returns an error:
module.js:338
    throw err;
          ^
Error: Cannot find module 'arraybuffer-slice'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Users\sgarcia\code\my-keepass\node_modules\kdbxweb\lib\format\kdbx.js:3:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

Are there any demos on how to get this to work? Thanks

**Comment by antelle** [comment]
Hello! Yes, it should be working.
It's can be loaded successfully in https://antelle.github.io/keeweb/ and in node.js (see the build on travis).
How are you trying to load it, which loader did you use? It looks like encoding trouble. 
About node environment: please, try to load the file itself: `node --eval "require('./dist/kdbxweb')"` - for me, it works ok.

**Comment by sgarcia-dev** [comment]
Your chrome example worked perfectly using the cdn at https://cdn.rawgit.com/antelle/kdbxweb/master/dist/kdbxweb.js . I just switched out the dist/kdbxweb.js for that and it loaded without issues, how strange...but thanks!

I think I'll skip the node version for now since I was primarily wanting to use this with browserify to run it on the browser. Either way, do you have any kind of todos you might need help with? Maybe with more documentation? 

I just found quite a big lack of decent keepass javascript api's and with lastpass's recent infiltration and purchase by logme inm and 1password's pretty high prices, Keepass needs even more applications to make it more popular, and helping this api grow seems a step in the right direction

**Comment by antelle** [comment]
I fugured it out: version in npm had bad dependency, and you were installing from npm. Fixed in be0c58a8dab87601833b2915db10c5be5206674f (0.1.19), thanks for this!
Now it loads ok, please check. A quick example is in readme: https://github.com/antelle/kdbxweb#usage but yes, the documentation is not so good yet, I'll try to write more docs to make it more friendly.
Exactly for this core library I have implemented almost all features (some of them need testing though). I've used this in a commercial project but there was used only basic functional: loading, reading entries. More advanced examples - like writing binaries, ... - likely to have bugs in them and should be tested. I'm planning to test them with my KeePass GUI project, https://github.com/antelle/keeweb

**Comment by antelle** [comment]
Closing as resolved, as it's loading for me. If it still doesn't help for you - please, reopen.

**Comment by sgarcia-dev** [comment]
Oh alright, that's awesome. I already checked keeweb and it's pretty sleek looking. I was hoping to build a port of it with material design and ionic (current android app offerings are very ugly/lack a lot of features). 

If you don't mind contributions, it would be nice to add a contributing section with things that need doing, even if it's only with things like documentation and more examples, that way you can focus on more important things. Either way, best of luck!

**Comment by antelle** [comment]
Thanks, I'll add contributing section.
I agree, current mobile apps looks ugly, as well as all mac osx ports existing now - that's why I've decided to create a javascript port hoping that it's easer to develop and style than a native app.
My plans for this webapp include mobile app and webapp (I've already created a desktop app with electron). Good luck with your port! If you'll find some missing features in the library - please, don't hesitate to open an issue or pullreq.
